/**
 * Comment or uncomment predefined capabilities.
 */
module.exports = [
  // {
  //   browserName: "Chrome",
  //   name: "bs-test",
  //   build: "bs-test-1",
  //   "browserstack.debug": true,
  //   browserVersion: "latest",
  //   resolution: "1024x768",
  //   "browserstack.selenium_version": "4.1.0",
  //   os: "OS X",
  //   osVersion: "Big Sur",
  // },
  // {
  //   browserName: "Chrome",
  //   name: "bs-test",
  //   build: "bs-test-1",
  //   "browserstack.debug": true,
  //   browserVersion: "latest",
  //   resolution: "1024x768",
  //   "browserstack.selenium_version": "4.1.0",
  //   os: "Windows",
  //   osVersion: "10",
  //   realMobile: "false",
  // },
  // {
  //   browserName: "Edge",
  //   name: "bs-test",
  //   build: "bs-test-1",
  //   "browserstack.debug": true,
  //   browserVersion: "latest",
  //   resolution: "1024x768",
  //   "browserstack.selenium_version": "4.1.0",
  //   os: "OS X",
  //   osVersion: "Big Sur",
  // },
  {
    browserName: "Edge",
    name: "bs-test",
    build: "bs-test-1",
    "browserstack.debug": true,
    browserVersion: "latest",
    resolution: "1024x768",
    "browserstack.selenium_version": "4.1.0",
    os: "Windows",
    osVersion: "10",
    realMobile: "false",
  },
  {
    browserName: "Firefox",
    name: "bs-test",
    build: "bs-test-1",
    "browserstack.debug": true,
    browserVersion: "latest",
    resolution: "1024x768",
    "browserstack.selenium_version": "4.1.0",
    os: "Windows",
    osVersion: "10",
    realMobile: "false",
  },
  // {
  //   browserName: "Firefox",
  //   name: "bs-test",
  //   build: "bs-test-1",
  //   "browserstack.debug": true,
  //   browserVersion: "latest",
  //   resolution: "1024x768",
  //   "browserstack.selenium_version": "4.1.0",
  //   os: "OS X",
  //   osVersion: "Big Sur",
  // },
];
